### PR TITLE
chore(package): allow Webpack 2.2.0 rc as peerDep

### LINKED ISSUE #186: Update webpack peerDependency with rc
**I'm submitting a bug report**

**Webpack version:**
2.2.0-rc.0

**Webpack Karma version**:
1.8

**Current behavior:**

PeerDependency failure

**Expected/desired behavior:**

exit 0

### PR DESCRIPTION
**Pull request by d3viant0ne**
Resolves #186

//cc @MikaAK - This will need to be published for those wanting to use the Webpack Release Cnadidate

### CODE REVIEW

**Comment by graingert** [comment]
Cnadidate -> Candidate

**Comment by graingert** [comment]
@MikaAK can you merge this in and make a release?

**Comment by d3viant0ne** [comment]
@graingert - He left a note in the issue

**Comment by graingert** [comment]
Sweet

**Pull request merged**
