### PR TITLE
Fix webpackServer config key in README

### PR DESCRIPTION
**Pull request by nkbt**
Changed configuration key from webpackMiddleware to actually working webpackServer

### CODE REVIEW

**Comment by marr** [comment]
:+1:

**Comment by sokra** [comment]
huh? Why isn't `webpackMiddleware` working?

**Comment by marr** [comment]
Im not sure - But the options to the server weren't being sent with webpackMiddleware in my karma.config.js. Here is a gist of the karma config if it matters: https://gist.github.com/880a91d831b02ed02daa

**Comment by ColCh** [comment]
This is working  ... From my karma config:
```js
    webpackMiddleware: {
      stats: {
        // With console colors
        colors: true,
        // add the hash of the compilation
        hash: false,
        // add webpack version information
        version: false,
        // add timing information
        timings: true,
        // add assets information
        assets: false,
        // add chunk information
        chunks: false,
        // add built modules information to chunk information
        chunkModules: false,
        // add built modules information
        modules: false,
        // add also information about cached (not built) modules
        cached: false,
        // add information about the reasons why modules are included
        reasons: false,
        // add the source code of modules
        source: true,
        // add details to errors (like resolving log)
        errorDetails: true,
        // add the origins of chunks and chunk merging info
        chunkOrigins: true,
        // Add messages from child loaders
        children: false
      }
    },
```

**Comment by marr** [comment]
confirmed that webpackMiddleware is working in 1.7.2.

**Pull request closed without merging**
